### ISSUE TITLE
How to work with a forked repo?

### ISSUE THREAD

**Issue by drmingdrmer** [ejoffe/spr#204]
Update 2022-03-17:
`spr` does not work with forked repo: it has to create a PR that is based on a branch in the repo. The second PR has to base on the branch of the first PR. 

---

Hello guys, I'm new to this tool. It looks very useful and damn simple to use.
But I can not find a way to config it to work with a forked repo.

The upstream repo is: `datafuselabs/openraft`.
I forked it into: `drmingdrmer/openraft`.

The `git remote` config of my forked repo is:
```
git remote -v
origin  git@github.com:drmingdrmer/openraft.git (fetch)
origin  git@github.com:drmingdrmer/openraft.git (push)
ups     git@github.com:datafuselabs/openraft.git (fetch)
ups     git@github.com:datafuselabs/openraft.git (push)
```

The `.spr.yml` in my forked repo is:
```yaml
githubRepoOwner: drmingdrmer
githubRepoName: openraft
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: ups
githubBranch: main
mergeMethod: rebase
```

### The Problem

Then `git spr update` will create branch and PR in the upstream repo: `datafuselabs/openraft`.
By changing `githubRemote` to `origin`, it will just create a branch in the forked repo but also create PR in the forked repo.

What do I do to let it create **branch** in my forked repo `drmingdrmer/openraft` and create **PR** in the upstream repo `datafuselabs`?

Thanks guys:DD
