### ISSUE TITLE
.spr.yml is overwritten with new values every time a git spr command is run.

### ISSUE THREAD

**Issue by jameskyle** [ejoffe/spr#410]
Steps to reproduce for 0.14.9:

# Run `git spr status` or something, it generates a config file that looks something like

```yaml
githubRepoOwner: TheOwner
githubRepoName: therepo
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: master
remoteBranches: []
mergeMethod: rebase
```

# Make some changes something like...

```yaml
githubRepoOwner: TheOwner
githubRepoName: therepo
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: develop
remoteBranches: []
mergeMethod: squash
```

# Run `git spr status` again

Works as expected. Changes retained. 

# Now add something new

```yaml
githubRepoOwner: TheOwner
githubRepoName: therepo
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: develop
remoteBranches: []
mergeMethod: squash
mergeQueue: true
```

# Now run `git status spr` one more time

It overwrites the config and removes the mergeQueue option going back to

```yaml
githubRepoOwner: TheOwner
githubRepoName: therepo
githubHost: github.com
requireChecks: true
requireApproval: true
githubRemote: origin
githubBranch: develop
remoteBranches: []
mergeMethod: squash
```

I also tested to remove something like githubBranch (which I understand should be auto-detected). It will overwrite the .spr.yml and set it to the default of `master`.
