### ISSUE TITLE
[feature request] Split config into repo-config and user-config

### ISSUE THREAD

**Issue by krdln** [ejoffe/spr#59]
Currently, the conf file looks like this:
```yaml
# repo settings
githubRepoOwner: asdf
githubRepoName: ijkl
requireChecks: true
requireApproval: true
cleanupRemoteBranch: true  # not sure about this one

# user settings
showPRLink: true
logGitCommands: false
logGitHubCalls: false
statusBitsHeader: true
```
This mixes per-repo settings and user settings. This is not perfect as:
* as an spr user, I'd like to tweak user settings globally,
* we keep the `.spr.yml` in the repo and having user settings there seems really weird (and causes a PR on each spr update).

Alternatively – merge spr yamls from different locations?

cc @kwapik @GregoRCodi
